### ISSUE TITLE
Build is failing: Unhandled open contour

### ISSUE THREAD

**Issue by eliheuer** [SorkinType/Danfo#1]
A unhandled open contour is making the build fail: https://github.com/SorkinType/Danfo/actions/runs/5061369100/jobs/9085484402
```
Traceback (most recent call last):
  File "/home/runner/work/Danfo/Danfo/venv/bin/gftools", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/gftools/scripts/__init__.py", line 91, in main
    mod.main(args[2:])
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line 672, in main
    builder.build()
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line 212, in build
    self.build_static()
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line [46](https://github.com/SorkinType/Danfo/actions/runs/5061369100/jobs/9085484402#step:10:47)1, in build_static
    self.build_a_static_format("otf", self.config["otDir"], self.post_process)
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line 516, in build_a_static_format
    for fontfile in self.run_fontmake(source, args):
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line 389, in run_fontmake
    FontProject().run_from_glyphs(source, **args)
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 839, in run_from_glyphs
    self.run_from_designspace(
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 1113, in run_from_designspace
    self._run_from_designspace_static(
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 1200, in _run_from_designspace_static
    self.run_from_ufos(
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 1283, in run_from_ufos
    self.build_otfs(ufos, cff_version=cff_version, **kwargs)
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 279, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 620, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "/home/runner/work/Danfo/Danfo/venv/lib/python3.8/site-packages/fontmake/font_project.py", line [47](https://github.com/SorkinType/Danfo/actions/runs/5061369100/jobs/9085484402#step:10:48)9, in _iter_compile
    raise FontmakeError("Compiling UFO failed", ufo.path) from e
fontmake.errors.FontmakeError: In 'Danfo.glyphs' -> 'master_ufo/Danfo-Regular.designspace' -> 'master_ufo/Danfo-Regular.ufo': Compiling UFO failed: Unhandled open contour
make: *** [Makefile:22: build.stamp] Error 1
Error: Process completed with exit code 2.
```

**Comment by eliheuer** [comment]
Fixed in PR #3
